/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/generate_api_types.py
 */

import type { components } from "./types.generated";

// State
export type AppStateResponse = components["schemas"]["AppStateResponse"];
export type ModuleSnapshot = components["schemas"]["ModuleSnapshot"];
export type ModuleUI = components["schemas"]["ModuleUI"];

// Modules
export type ModuleUIResponse = components["schemas"]["ModuleUIResponse"];
export type ModuleTileResponse = components["schemas"]["ModuleTileResponse"];
export type ModuleModalsResponse = components["schemas"]["ModuleModalsResponse"];
export type ModuleInfo = components["schemas"]["ModuleInfo"];
export type ModuleListResponse = components["schemas"]["ModuleListResponse"];
export type ModuleToggleResponse = components["schemas"]["ModuleToggleResponse"];

// Auth
export type PairRequest = components["schemas"]["PairRequest"];
export type PairResponse = components["schemas"]["PairResponse"];
export type SuccessResponse = components["schemas"]["SuccessResponse"];

// Health
export type HealthResponse = components["schemas"]["HealthResponse"];
export type InfoResponse = components["schemas"]["InfoResponse"];
