/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Modules
         * @description List all registered modules with their current state
         */
        get: operations["list_modules_api_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Module
         * @description Enable a registered module
         */
        post: operations["enable_module_api_modules__name__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable Module
         * @description Disable an enabled module
         */
        post: operations["disable_module_api_modules__name__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair
         * @description Exchange a pairing code for an API token
         */
        post: operations["pair_api_auth_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/unpair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpair
         * @description Unpair the app from this NAS. Requires authentication
         */
        post: operations["unpair_api_auth_unpair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Modules
         * @description List all available modules from marketplace
         */
        get: operations["list_modules_api_marketplace_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Module
         * @description Get detailed information about a specific module
         */
        get: operations["get_module_api_marketplace_modules__module_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Registry
         * @description Force refresh the marketplace registry cache
         */
        post: operations["refresh_registry_api_marketplace_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Module Ui
         * @description Get full UI for a module (tile + modals)
         */
        get: operations["get_module_ui_api_modules__name__ui_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/tile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Module Tile
         * @description Get just the tile for a module
         */
        get: operations["get_module_tile_api_modules__name__tile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/modals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Module Modals
         * @description Get just the modals for a module
         */
        get: operations["get_module_modals_api_modules__name__modals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/action/{action_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invoke Action
         * @description Invoke an action on a module
         */
        post: operations["invoke_action_api_modules__name__action__action_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{name}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Module Actions
         * @description List available actions for a module
         */
        get: operations["list_module_actions_api_modules__name__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App State
         * @description Get full application state
         */
        get: operations["get_app_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Info
         * @description Server information
         */
        get: operations["info_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionRef
         * @description Reference to a callable action
         */
        ActionRef: {
            /** Action */
            __action__: string;
        };
        /**
         * AlertSchema
         * @description Alert message
         */
        AlertSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "alert";
            /** Message */
            message: string;
            /**
             * Variant
             * @default info
             * @enum {string}
             */
            variant: "info" | "success" | "warning" | "error";
            /** Title */
            title?: string | null;
        };
        /**
         * AppStateResponse
         * @description Full application state response
         */
        AppStateResponse: {
            /** Modules */
            modules: components["schemas"]["ModuleSnapshot"][];
            /** Active Modal */
            active_modal?: string | null;
        };
        /**
         * BadgeSchema
         * @description Small label badge
         */
        BadgeSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "badge";
            /** Text */
            text: string;
            /**
             * Variant
             * @default default
             * @enum {string}
             */
            variant: "default" | "primary" | "success" | "warning" | "error" | "info";
        };
        /**
         * ButtonSchema
         * @description Clickable button
         */
        ButtonSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "button";
            /** Label */
            label: string;
            on_click?: components["schemas"]["ActionRef"] | null;
            /**
             * Variant
             * @default primary
             * @enum {string}
             */
            variant: "primary" | "secondary" | "ghost" | "danger";
            /**
             * Size
             * @default md
             * @enum {string}
             */
            size: "sm" | "md" | "lg";
            /** Icon */
            icon?: string | null;
            /**
             * Icon Only
             * @default false
             */
            icon_only: boolean;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /**
             * Loading
             * @default false
             */
            loading: boolean;
        };
        /**
         * CardSchema
         * @description Card container with optional header and footer
         */
        CardSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "card";
            /** Icon */
            icon?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Children
             * @default []
             */
            children: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[];
            /** Footer */
            footer?: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[] | null;
        };
        /**
         * CheckboxSchema
         * @description Checkbox input
         */
        CheckboxSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "checkbox";
            /** Name */
            name: string;
            /** Label */
            label?: string | null;
            /**
             * Checked
             * @default false
             */
            checked: boolean;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
        };
        /**
         * GridSchema
         * @description CSS Grid layout
         */
        GridSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "grid";
            /**
             * Columns
             * @default 2
             */
            columns: number | string;
            /**
             * Gap
             * @default 4
             * @enum {string}
             */
            gap: "0" | "1" | "2" | "3" | "4" | "5" | "6" | "8";
            /**
             * Children
             * @default []
             */
            children: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /**
         * InfoResponse
         * @description Server information response
         */
        InfoResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * InputSchema
         * @description Text input field
         */
        InputSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "input";
            /** Name */
            name: string;
            /** Label */
            label?: string | null;
            /**
             * Value
             * @default
             */
            value: string;
            /**
             * Input Type
             * @default text
             * @enum {string}
             */
            input_type: "text" | "password" | "email" | "number";
            /** Placeholder */
            placeholder?: string | null;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
        };
        /**
         * ModalSchema
         * @description Modal dialog
         */
        ModalSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "modal";
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Children
             * @default []
             */
            children: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[];
            /** Footer */
            footer?: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[] | null;
            /**
             * Closable
             * @default true
             */
            closable: boolean;
        };
        /**
         * ModuleInfo
         * @description Information about a module
         */
        ModuleInfo: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Initialized */
            initialized: boolean;
            /** Source */
            source: string;
            /** Removable */
            removable: boolean;
            /** Version */
            version: string;
            /** System Deps */
            system_deps: string[];
        };
        /**
         * ModuleListResponse
         * @description Response listing all modules
         */
        ModuleListResponse: {
            /** Modules */
            modules: components["schemas"]["ModuleInfo"][];
        };
        /**
         * ModuleModalsResponse
         * @description Modals-only response for a module
         */
        ModuleModalsResponse: {
            /** Module */
            module: string;
            /** Modals */
            modals: components["schemas"]["ModalSchema"][];
        };
        /**
         * ModuleSnapshot
         * @description Snapshot of a module's current state including UI
         */
        ModuleSnapshot: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Initialized */
            initialized: boolean;
            ui?: components["schemas"]["ModuleUI"] | null;
        };
        /**
         * ModuleTileResponse
         * @description Tile-only response for a module
         */
        ModuleTileResponse: {
            /** Module */
            module: string;
            tile: components["schemas"]["TileSchema"];
        };
        /**
         * ModuleToggleResponse
         * @description Response for module enable/disable toggle
         */
        ModuleToggleResponse: {
            /** Success */
            success: boolean;
            /** Module */
            module: string;
            /** Enabled */
            enabled: boolean;
        };
        /**
         * ModuleUI
         * @description Full UI state for a module
         */
        ModuleUI: {
            tile?: components["schemas"]["TileSchema"] | null;
            /**
             * Modals
             * @default []
             */
            modals: components["schemas"]["ModalSchema"][];
        };
        /**
         * ModuleUIResponse
         * @description Full UI response for a module
         */
        ModuleUIResponse: {
            /** Module */
            module: string;
            ui: components["schemas"]["ModuleUI"];
        };
        /**
         * PairRequest
         * @description Request to pair with the NAS
         */
        PairRequest: {
            /** Pairing Code */
            pairing_code: string;
        };
        /**
         * PairResponse
         * @description Response containing API token after successful pairing
         */
        PairResponse: {
            /** Success */
            success: boolean;
            /** Api Token */
            api_token: string;
            /** Message */
            message: string;
        };
        /**
         * ProgressSchema
         * @description Progress bar with optional labels
         */
        ProgressSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
            /** Value */
            value: number;
            /**
             * Max
             * @default 100
             */
            max: number;
            /** Label */
            label?: string | null;
            /** Sublabel */
            sublabel?: string | null;
            /**
             * Color
             * @default default
             * @enum {string}
             */
            color: "default" | "success" | "warning" | "error";
            /**
             * Size
             * @default sm
             * @enum {string}
             */
            size: "sm" | "lg";
        };
        /**
         * SelectOptionSchema
         * @description Option for Select component
         */
        SelectOptionSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "select_option";
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /**
         * SelectSchema
         * @description Dropdown select
         */
        SelectSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "select";
            /** Name */
            name: string;
            /** Label */
            label?: string | null;
            /** Options */
            options: components["schemas"]["SelectOptionSchema"][];
            /** Value */
            value?: string | null;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
        };
        /**
         * SpinnerSchema
         * @description Loading spinner
         */
        SpinnerSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "spinner";
            /**
             * Size
             * @default md
             * @enum {string}
             */
            size: "sm" | "md" | "lg";
            /** Label */
            label?: string | null;
        };
        /**
         * StackSchema
         * @description Flex container for vertical or horizontal layouts
         */
        StackSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stack";
            /**
             * Direction
             * @default vertical
             * @enum {string}
             */
            direction: "horizontal" | "vertical";
            /**
             * Gap
             * @default 4
             * @enum {string}
             */
            gap: "0" | "1" | "2" | "3" | "4" | "5" | "6" | "8";
            /**
             * Align
             * @default stretch
             * @enum {string}
             */
            align: "start" | "center" | "end" | "stretch";
            /**
             * Justify
             * @default start
             * @enum {string}
             */
            justify: "start" | "center" | "end" | "between" | "around";
            /**
             * Children
             * @default []
             */
            children: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[];
        };
        /**
         * StatCardSchema
         * @description Standalone stat card with icon and optional trend
         */
        StatCardSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stat_card";
            /** Label */
            label: string;
            /** Value */
            value: string | number;
            /** Icon */
            icon?: string | null;
            /**
             * Color
             * @default default
             * @enum {string}
             */
            color: "default" | "success" | "warning" | "error";
            /** Trend */
            trend?: [
                "up" | "down",
                string
            ] | null;
        };
        /**
         * StatSchema
         * @description Inline stat display (value + label) for tiles
         */
        StatSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stat";
            /** Label */
            label: string;
            /** Value */
            value: string | number;
        };
        /**
         * SuccessResponse
         * @description Generic success response
         */
        SuccessResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /**
         * TableColumnSchema
         * @description Column definition for Table
         */
        TableColumnSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table_column";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Width */
            width?: string | null;
            /**
             * Align
             * @default left
             * @enum {string}
             */
            align: "left" | "center" | "right";
        };
        /**
         * TableSchema
         * @description Data table
         */
        TableSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Columns */
            columns: components["schemas"]["TableColumnSchema"][];
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            /**
             * Empty Message
             * @default No data
             */
            empty_message: string;
        };
        /**
         * TextSchema
         * @description Text with styling variants
         */
        TextSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Content */
            content: string;
            /**
             * Variant
             * @default body
             * @enum {string}
             */
            variant: "body" | "secondary" | "muted" | "code";
        };
        /**
         * TileSchema
         * @description Module tile - specialized card for dashboard modules
         */
        TileSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tile";
            /** Icon */
            icon: string;
            /** Title */
            title: string;
            badge?: components["schemas"]["BadgeSchema"] | null;
            /**
             * Stats
             * @default []
             */
            stats: components["schemas"]["StatSchema"][];
            /** Content */
            content?: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[] | null;
            /**
             * Actions
             * @default []
             */
            actions: (components["schemas"]["StackSchema"] | components["schemas"]["GridSchema"] | components["schemas"]["CardSchema"] | components["schemas"]["TileSchema"] | components["schemas"]["StatSchema"] | components["schemas"]["TextSchema"] | components["schemas"]["StatCardSchema"] | components["schemas"]["ProgressSchema"] | components["schemas"]["BadgeSchema"] | components["schemas"]["TableSchema"] | components["schemas"]["TableColumnSchema"] | components["schemas"]["ButtonSchema"] | components["schemas"]["InputSchema"] | components["schemas"]["SelectSchema"] | components["schemas"]["SelectOptionSchema"] | components["schemas"]["ToggleSchema"] | components["schemas"]["CheckboxSchema"] | components["schemas"]["ModalSchema"] | components["schemas"]["AlertSchema"] | components["schemas"]["SpinnerSchema"])[];
        };
        /**
         * ToggleSchema
         * @description Toggle switch
         */
        ToggleSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "toggle";
            /** Name */
            name: string;
            /** Label */
            label?: string | null;
            /**
             * Checked
             * @default false
             */
            checked: boolean;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_modules_api_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleListResponse"];
                };
            };
        };
    };
    enable_module_api_modules__name__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_module_api_modules__name__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_api_auth_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpair_api_auth_unpair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    list_modules_api_marketplace_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_module_api_marketplace_modules__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_registry_api_marketplace_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_module_ui_api_modules__name__ui_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleUIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_tile_api_modules__name__tile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleTileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_modals_api_modules__name__modals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleModalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoke_action_api_modules__name__action__action_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                action_name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_module_actions_api_modules__name__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStateResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    info_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
}
