/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/generate_api_types.py
 */

import type { components } from "./types.generated";

// Helper types
export type ActionRef = components["schemas"]["ActionRef"];

// Layout components
export type StackSchema = components["schemas"]["StackSchema"];
export type GridSchema = components["schemas"]["GridSchema"];

// Card components
export type CardSchema = components["schemas"]["CardSchema"];
export type TileSchema = components["schemas"]["TileSchema"];
export type StatSchema = components["schemas"]["StatSchema"];

// Display components
export type TextSchema = components["schemas"]["TextSchema"];
export type StatCardSchema = components["schemas"]["StatCardSchema"];
export type StatSmallSchema = components["schemas"]["StatSmallSchema"];
export type ProgressSchema = components["schemas"]["ProgressSchema"];
export type SegmentedProgressSchema = components["schemas"]["SegmentedProgressSchema"];
export type SegmentedProgressSegmentSchema = components["schemas"]["SegmentedProgressSegmentSchema"];
export type LineChartSchema = components["schemas"]["LineChartSchema"];
export type ImageSchema = components["schemas"]["ImageSchema"];
export type BadgeSchema = components["schemas"]["BadgeSchema"];
export type TableSchema = components["schemas"]["TableSchema"];
export type TableColumnSchema = components["schemas"]["TableColumnSchema"];

// Interactive components
export type ButtonSchema = components["schemas"]["ButtonSchema"];
export type InputSchema = components["schemas"]["InputSchema"];
export type SelectSchema = components["schemas"]["SelectSchema"];
export type SelectOptionSchema = components["schemas"]["SelectOptionSchema"];
export type ToggleSchema = components["schemas"]["ToggleSchema"];
export type CheckboxSchema = components["schemas"]["CheckboxSchema"];
export type TabsSchema = components["schemas"]["TabsSchema"];
export type TabSchema = components["schemas"]["TabSchema"];

// Modal components
export type ModalSchema = components["schemas"]["ModalSchema"];

// Feedback components
export type AlertSchema = components["schemas"]["AlertSchema"];
export type SpinnerSchema = components["schemas"]["SpinnerSchema"];

// Component union type
export type ComponentSchema =
	  StackSchema
	| GridSchema
	| CardSchema
	| TileSchema
	| StatSchema
	| TextSchema
	| StatCardSchema
	| StatSmallSchema
	| ProgressSchema
	| SegmentedProgressSchema
	| SegmentedProgressSegmentSchema
	| LineChartSchema
	| ImageSchema
	| BadgeSchema
	| TableSchema
	| TableColumnSchema
	| ButtonSchema
	| InputSchema
	| SelectSchema
	| SelectOptionSchema
	| ToggleSchema
	| CheckboxSchema
	| TabsSchema
	| TabSchema
	| ModalSchema
	| AlertSchema
	| SpinnerSchema;

export type ComponentType = ComponentSchema["type"];

export function isComponentType<T extends ComponentType>(
	node: ComponentSchema,
	type: T
): node is Extract<ComponentSchema, { type: T }> {
	return node.type === type;
}