import json
import sys
from pathlib import Path

# Add backend to path
backend_path = Path(__file__).parent.parent / "backend"
sys.path.insert(0, str(backend_path))

from ContaraNAS.api.app import create_app

# UI Component schemas
UI_COMPONENTS = {
    "layout": ["StackSchema", "GridSchema"],
    "card": ["CardSchema", "TileSchema", "StatSchema"],
    "display": [
        "TextSchema",
        "StatCardSchema",
        "StatSmallSchema",
        "ProgressSchema",
        "SegmentedProgressSchema",
        "SegmentedProgressSegmentSchema",
        "LineChartSchema",
        "BadgeSchema",
        "TableSchema",
        "TableColumnSchema",
    ],
    "interactive": [
        "ButtonSchema",
        "InputSchema",
        "SelectSchema",
        "SelectOptionSchema",
        "ToggleSchema",
        "CheckboxSchema",
        "TabsSchema",
        "TabSchema",
    ],
    "modal": ["ModalSchema"],
    "feedback": ["AlertSchema", "SpinnerSchema"],
}

# Helper types
HELPER_TYPES = ["ActionRef"]

# API Response/Request schemas
API_SCHEMAS = {
    "state": ["AppStateResponse", "ModuleSnapshot", "ModuleUI"],
    "modules": [
        "ModuleUIResponse",
        "ModuleTileResponse",
        "ModuleModalsResponse",
        "ModuleInfo",
        "ModuleListResponse",
        "ModuleToggleResponse",
    ],
    "auth": ["PairRequest", "PairResponse", "SuccessResponse"],
    "health": ["HealthResponse", "InfoResponse"],
}

HEADER = """\
/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/generate_api_types.py
 */
"""


def generate_ui_ts(available: list[str]) -> str:
    """Generate ui.ts with UI component types."""
    lines = [HEADER, 'import type { components } from "./types.generated";', ""]

    # Helper types first
    helpers = [h for h in HELPER_TYPES if h in available]
    if helpers:
        lines.append("// Helper types")
        for name in helpers:
            lines.append(f'export type {name} = components["schemas"]["{name}"];')
        lines.append("")

    all_components = []

    for category, schemas in UI_COMPONENTS.items():
        present = [s for s in schemas if s in available]
        if not present:
            continue

        lines.append(f"// {category.replace('_', ' ').title()} components")
        for name in present:
            lines.append(f'export type {name} = components["schemas"]["{name}"];')
            all_components.append(name)
        lines.append("")

    # Component union
    lines.append("// Component union type")
    lines.append("export type ComponentSchema =")
    for i, name in enumerate(all_components):
        prefix = "\t| " if i > 0 else "\t  "
        suffix = ";" if i == len(all_components) - 1 else ""
        lines.append(f"{prefix}{name}{suffix}")
    lines.append("")

    # Type discriminator
    lines.append('export type ComponentType = ComponentSchema["type"];')
    lines.append("")

    # Type guard
    lines.append("export function isComponentType<T extends ComponentType>(")
    lines.append("\tnode: ComponentSchema,")
    lines.append("\ttype: T")
    lines.append("): node is Extract<ComponentSchema, { type: T }> {")
    lines.append("\treturn node.type === type;")
    lines.append("}")

    return "\n".join(lines)


def generate_responses_ts(available: list[str]) -> str:
    """Generate responses.ts with API response/request types."""
    lines = [HEADER, 'import type { components } from "./types.generated";', ""]

    for category, schemas in API_SCHEMAS.items():
        present = [s for s in schemas if s in available]
        if not present:
            continue

        lines.append(f"// {category.replace('_', ' ').title()}")
        for name in present:
            lines.append(f'export type {name} = components["schemas"]["{name}"];')
        lines.append("")

    return "\n".join(lines)


def generate_index_ts() -> str:
    """Generate index.ts that re-exports everything."""
    lines = [
        HEADER,
        "// UI component types",
        "export * from './ui';",
        "",
        "// API response/request types",
        "export * from './responses';",
        "",
        "// Raw OpenAPI types for advanced usage",
        'export type { components, operations, paths } from "./types.generated";',
    ]
    return "\n".join(lines)


def main():
    """Generate OpenAPI schema and TypeScript type files."""
    app = create_app()
    schema = app.openapi()

    frontend_path = Path(__file__).parent.parent / "frontend"
    api_path = frontend_path / "src" / "lib" / "api"
    api_path.mkdir(parents=True, exist_ok=True)

    # Write OpenAPI schema JSON
    openapi_path = frontend_path / "openapi.json"
    openapi_path.write_text(json.dumps(schema, indent=2))
    print(f"Generated {openapi_path}")

    # Get available schemas
    available = list(schema.get("components", {}).get("schemas", {}).keys())

    # Generate type files
    (api_path / "ui.ts").write_text(generate_ui_ts(available))
    print(f"Generated {api_path / 'ui.ts'}")

    (api_path / "responses.ts").write_text(generate_responses_ts(available))
    print(f"Generated {api_path / 'responses.ts'}")

    (api_path / "index.ts").write_text(generate_index_ts())
    print(f"Generated {api_path / 'index.ts'}")


if __name__ == "__main__":
    main()
